/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-09-22 07:00:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import TodoMemo.BoardMemo;
import java.util.ArrayList;

public final class memo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("TodoMemo.BoardMemo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("  @import url('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap');\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("font-family: 'Open Sans', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrap {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("	background: #e1dfdd;\r\n");
      out.write("	height: 1px;\r\n");
      out.write("	border: 0;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 48px;\r\n");
      out.write("	background-color: #2564cf;\r\n");
      out.write("	/*border: 1px solid black;*/\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header img {\r\n");
      out.write("	width: 15px;\r\n");
      out.write("	height: 15px;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	margin-top: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .title {\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-left: 40px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 12px;\r\n");
      out.write("	left: 3px;	​\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logOutIcon {\r\n");
      out.write("	width: 35px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 10px;\r\n");
      out.write("	top: -8px;\r\n");
      out.write("	filter: invert(100%) sepia(0%) saturate(7499%) hue-rotate(169deg)\r\n");
      out.write("		brightness(125%) contrast(98%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	width: 293px;\r\n");
      out.write("	heigt: 20px;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	font-size: 56px;\r\n");
      out.write("	margin-top: 66px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbclass {\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 500px;\r\n");
      out.write("  margin: 1rem auto;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 행 */\r\n");
      out.write(".test, th,  {\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  border-bottom: 1px solid #ddd;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("  background-color: #1b1b1b;\r\n");
      out.write("  color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 올렸을 때 */\r\n");
      out.write("tbody tr:hover {\r\n");
      out.write("  background-color: #d3d3d3;\r\n");
      out.write("  opacity: 0.9;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 비율 */\r\n");
      out.write("th:nth-child(1),\r\n");
      out.write("td:nth-child(1) {\r\n");
      out.write("  width: 15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th:nth-child(2),\r\n");
      out.write("td:nth-child(2) {\r\n");
      out.write("  width: 55%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th:nth-child(3),\r\n");
      out.write("td:nth-child(3) {\r\n");
      out.write("  width: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:nth-child(even) {\r\n");
      out.write("  background-color: #fff6f6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modify {\r\n");
      out.write("	width: 58px;\r\n");
      out.write("	height: 26px;	\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("	background-color: #0078d4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete {\r\n");
      out.write("	width: 58px;\r\n");
      out.write("	height: 26px;\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("	background-color: #0078d4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register {\r\n");
      out.write("	width: 58px;\r\n");
      out.write("	height: 26px;\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("	background-color: #0078d4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".goHome {\r\n");
      out.write("	width: 58px;\r\n");
      out.write("	height: 26px;\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("	background-color: #0078d4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modify:hover{\r\n");
      out.write("	background:blue;\r\n");
      out.write("	color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete:hover{\r\n");
      out.write("	background:blue;\r\n");
      out.write("	color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register:hover{\r\n");
      out.write("	background:blue;\r\n");
      out.write("	color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".goHome:hover{\r\n");
      out.write("	background:blue;\r\n");
      out.write("	color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".regBtn {\r\n");
      out.write("	margin-left: 19px;\r\n");
      out.write("	width: 350px;\r\n");
      out.write("	height: 32px;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	border: 0;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	background-color: rgb(233, 233, 233);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<img\r\n");
      out.write("		src=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCABUAFUDASIAAhEBAxEB/8QAGwABAAMBAQEBAAAAAAAAAAAAAAQFBgMCAQf/xAArEAACAgEDAgUEAgMAAAAAAAABAgADBAUREgYxEyFBUZEyYXGhIoEUQrH/xAAZAQACAwEAAAAAAAAAAAAAAAADBAABAgX/xAAfEQADAQEBAQADAQEAAAAAAAAAAQIRAxIxBCFhEzL/2gAMAwEAAhEDEQA/AISqzsFUEsTsAPWWqdPZroGJqQn/AFZjv+hPHTyo2prz23Ckr+Zro927VDxC3PmqWsweTjW4tprvQqw/c5TSdUKngUN5c+RA/G0zcPzv3Og7ny8OuNjW5VoroQsx/UsX6ezUQsDU5H+qsd/2JO6XVPAvby58gD+Npexbr3qaxBY5prWfn7KyMVYEMDsQfSfJZ9Qqi6m3DbcqC35lZGpr1KYFrHhLwtNyM4nwVAUd2Y7CdsvRMvFqNjBLFHfgd9po9HVF0zH4bbFdzt7+smEAgg9vWKV+RSr+B1yTR+fxOmQFXItCfSHIH43iOi58qtem1bK24up3Bl2nUzhALMZWf1IfYfG0oYmK5zf/AEjSpz8JOdnW513iXEeXkqjsBI0RNpJLEZb0k4Odbg3eJSR5+TKexEtX6mcoRXjKr+hL7j42lDExXOKetGldL9I922vda1ljcnY7kzxETZksdN1e7AU18RZV34k7bfgyRl9Q3X1GumoU8vIty3P9SmiDfKG9aNe6SzRERCGTrjY75V6U1DdmPxNCnTWOEHiXWl/UrsB/yVegWpVqa8ztyUqD95r4p36VNYg/KE1rMXqenPp9oUtzRvpbaQpouqLU8Omrf+fLlt7CZ2H5U6hNg7SVYibpmnPqFpUNwRfqbaXL9NY5Q+HdaH9C2xH/ACc+l7U8O6rf+fLlt7iX8V7dbV4g3OJc6zB5OO+Le9No2ZT8zlLLX7Ut1N+B34qFJ+8rY5DblNi9LHhb6Vopza/GvcpUewXuZKzOnEWkti2OXA34vsd/iWWjWpbplPA/QvEj2Ikx3VELuQFUbkmI12tWMzznyYAjY7GJ0vcWX2OvZmJHzE6Aqc5OTWM+tAi5DbD3AJ+SJBiU5T+otNr4erLHtcvYxdj3JO88xEso9V2PU4etijDsQdpMfWM+xCjZDbH2AB+QJBiU5T+otNr4IiJZR2xsu/Ectj2MhPfbsf6nTJ1LLyk4X3sy+wAA/UixK8rdwvX8EREsolabif5uYlJOy92P2msTTMKtAgxqiB6soJ+TMtpGWuHnJY/0EcWPsDNiliWIHrdWQ+YIPlEvyXSr+DHJLDMa7pteG6W0Datztx9jKiXfUWdVeUopYOEO7MO2/tKSM8vThegV56/Rb6FpteY723jetDtx9zL99MwrEKHGqAPqqgH5EpOnc6qgvRcwQOd1Y9t/aaN7ErQvY6qg8ySfKKd3asPzU+TF6lif4WY9IO691P2kWTdXy1zM57E+gDip9wJCjsb5W/Ras39Gl0XSaDjLkZCCx381DeYA/EmZmkYmRSVSlKn2/iyLt5/1OOhZ9V2JXQWC21jjxJ7j3EnZmZTh0my1wPLyX1J+0Qur/wBP6NSp8mIdSjsjd1OxiLXNlrue7MSf7idEUPMREhBERIQRESEEREhBERIQRESEP//Z\">\r\n");
      out.write("	<p class=\"title\">To Do Memo</p>\r\n");
      out.write("\r\n");
      out.write("	<a href=\"/TodoTeamProject/logout\"><img class=\"logOutIcon\"\r\n");
      out.write("		src=\"https://img.icons8.com/material/24/000000/exit.png\" alt=\"exit\" /></a>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=wrap>\r\n");
      out.write("		<h2>To do Memo</h2>\r\n");
      out.write("		");

		ArrayList<BoardMemo> list = (ArrayList<BoardMemo>) request.getAttribute("list");
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<table class=\"tbclass\">\r\n");
      out.write("			");

			int counter = 1;
			for (BoardMemo m : list) {
			
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.print(counter);
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(m.getM_contents());
      out.write("</td>\r\n");
      out.write("				<td class=\"test\">\r\n");
      out.write("					<form action=\"");
      out.print(request.getContextPath());
      out.write("/updateM\" method=\"get\">\r\n");
      out.write("						<!-- 수정 버튼을 클릭하면 메모의 정보를 수정 페이지로 전달 -->\r\n");
      out.write("						<input type=\"hidden\" name=\"code\" value=\"");
      out.print(m.getM_code());
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"contents\"\r\n");
      out.write("							value=\"");
      out.print(m.getM_contents());
      out.write("\">\r\n");
      out.write("						<button class=\"modify\">수정</button>\r\n");
      out.write("					</form>\r\n");
      out.write("					<form action=\"");
      out.print(request.getContextPath());
      out.write("/deleteM\" method=\"get\">\r\n");
      out.write("						<!-- 삭제 버튼을 클릭하면 메모의 코드를 삭제 servlet으로 전달 -->\r\n");
      out.write("						<input type=\"hidden\" name=\"del\" value=\"");
      out.print(m.getM_code());
      out.write("\"></input>\r\n");
      out.write("						<button class=\"delete\">삭제</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

			counter++;
			}
			
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"Reg\">\r\n");
      out.write("			<form action=\"");
      out.print(request.getContextPath());
      out.write("/registerM\" method=\"get\">\r\n");
      out.write("				<input class=\"regBtn\" type=\"text\" name=\"contents\"></input>\r\n");
      out.write("				<button class=register>등록</button>\r\n");
      out.write("			</form>\r\n");
      out.write("			<form action=\"");
      out.print(request.getContextPath());
      out.write("/main.do\" method=\"get\">\r\n");
      out.write("			<div class=\"wrapButton\">\r\n");
      out.write("				<input class=\"goHome\" type=\"submit\" value=\"홈으로\">\r\n");
      out.write("			</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
